name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install autoconf
      run: sudo apt-get install -y autoconf
      
    - name: Apply autoconf
      run: autoreconf -f -i
      
    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: sucrack-1.2.3
        path: sucrack-1.2.3.tar.gz
        retention-days: 1
